name: ree
version: stable
version-script: git -C parts/ree/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  Ree tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  ree:
    command: bin/ree
    environment:
        PYTHONIOENCODING: utf-8
  ree:
    command: bin/ree
    environment:
        PYTHONIOENCODING: utf-8

parts:
  ree:
    source: https://github.com/montyking/ree.git
    plugin: python
